
const data = {
    products: [
        {
            name: 'Shirt 1',
            slug: 'shirt-1',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 40,
            brand: 'Sucio',
            rating: 4.9,
            numReviews: 8,
            inStock: 20,
            description: 'High-quality cotton',
        },
        {
            name: 'Shirt 2',
            slug: 'shirt-2',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 40,
            brand: 'Sucio',
            rating: 4.7,
            numReviews: 5,
            inStock: 16,
            description: 'High-quality cotton',
        },
        {
            name: 'Shirt 3',
            slug: 'shirt-3',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 40,
            brand: 'Sucio',
            rating: 4.7,
            numReviews: 6,
            inStock: 18,
            description: 'High-quality cotton',
        },
        {
            name: 'Shirt 4',
            slug: 'shirt-4',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 40,
            brand: 'Sucio',
            rating: 4.8,
            numReviews: 6,
            inStock: 13,
            description: 'High-quality cotton',
        },
        {
            name: 'Shirt 5',
            slug: 'shirt-5',
            category: 'Shirts',
            image: '/images/shirt5.jpg',
            price: 40,
            brand: 'Sucio',
            rating: 4.9,
            numReviews: 10,
            inStock: 10,
            description: 'High-quality cotton',
        },
    ]
}

export default data;