import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
        <Head>
          <title>Sucio Store</title>
          <meta name="descripton" content="Generated by create next app"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <h1 className="text9xl font-bold">Sucio</h1>
    </div>
  )
}